services:
  - type: web
    name: yume-hyakuya
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn dream_server:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: SAKURA_API_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
